#!/usr/bin/env bash

# ensure dist dir exists
mkdir -p dist

if [ $1 -eq '0' ]; then
  rm dist/*
fi

function generate() {
  browser=$1
  ext=$2
  # get version from manifest
  version=$(cat "$browser/manifest.json" | grep -oP '(?<="version": ")[^"]*')
  # get file name, remove existing
  file="dist/quite-black-$version.$ext"
  if [ -f "$file" ]; then
    rm "$file"
  fi
  # create theme extension
  zip -j "$file" "$browser/manifest.json" "${@:3}"
}

generate chrome zip LICENSE
generate firefox xpi LICENSE
