#!/usr/bin/env sh

firefox_manifest=./firefox/manifest.json

# get version from manifest
version=$(cat "$firefox_manifest" | grep -oP '(?<="version": ")[^"]*')

# output .xpi file
mkdir -p dist
zip dist/quite-black-$version.xpi "$firefox_manifest"
