#!/usr/bin/env bash

print_help() {
  echo "usage: archive <options> [--] [file_paths...]"
  echo
  echo "arguments:"
  echo "  [file_paths...]         additional files to include in archive"
  echo
  echo "options:"
  echo "  -n, --dry-run           log only without performing operations (noop)"
  echo
  echo "      --name <name>       (required) name for logging"
  echo "  -d, --theme-dir <path>  (required) theme directory path"
  echo "  -o, --output <path>     (required) output file path"
  echo
  echo "  -h, --help              display help text"
}

if [ $# -eq 0 ]; then
  print_help
  exit 1
fi

name=
prefix=
theme_dir=
output_file=
dry_run=
args=()

error() {
  echo 1>&2 "${prefix}error: $1"
  exit "${2:-1}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
  -h | --help)
    print_help
    exit
    ;;
  -n | --dry-run)
    dry_run=1
    shift
    ;;
  --name)
    name="$2"
    shift
    shift

    [ -n "$name" ] && prefix="[$name] "
    ;;
  -d | --theme-dir)
    theme_dir="$2"
    shift
    shift
    ;;
  -o | --output)
    output_file="$2"
    shift
    shift
    ;;
  --)
    shift
    args=("$@")
    break
    ;;
  -*) error "unknown option: $1" ;;
  *) error "unknown argument: $1" ;;
  esac
done

[ -z "$name" ] && error "option '--name' is required"
[ -z "$theme_dir" ] && error "option '--theme-dir' is required"
[ -z "$output_file" ] && error "option '--output' is required"
[ ! -d "$theme_dir" ] && error "option '--theme-dir' not a directory: $theme_dir"

manifest_filename="manifest.json"
manifest_file="$theme_dir/$manifest_filename"
[ ! -f "$manifest_file" ] && error "not a file: $manifest_file"

version=$(grep -oP '(?<="version": ")[^"]*' "$manifest_file")
[ -z "$version" ] && error "unable to parse $manifest_filename version"

# get relative file paths from args
args+=("$manifest_file")
files=()

for arg in "${args[@]}"; do
  relative_file_path="$(realpath --relative-to="$theme_dir" "$arg")"

  if [ -n "$relative_file_path" ]; then
    files+=("$relative_file_path")
  fi
done

[ ${#files[@]} -eq 0 ] && error "no files to archive"

# replace __VERSION__ with actual version number
output_file="${output_file//__VERSION__/$version}"

echo "${prefix}theme info:"
printf "  %-11s : %s\n" "name" "$name"
printf "  %-11s : %s\n" "directory" "$theme_dir"
printf "  %-11s : %s\n" "version" "$version"
printf "  %-11s : %s\n" "output file" "$output_file"
printf "  %-11s : " "files (${#files[@]})"
echo "${files[@]}"
echo

if [ -f "$output_file" ]; then
  echo "${prefix}existing output file found. removing: $output_file"

  if [ -n "$dry_run" ]; then
    echo "${prefix}[dry-run] rm -v \"$output_file\""
  else
    rm -v "$output_file"
  fi

  echo
fi

echo "${prefix}creating zip: $output_file"

output_relative_path="$(realpath --relative-to="$theme_dir" "$output_file")"

if [ -n "$dry_run" ]; then
  echo "${prefix}[dry-run] cd \"$theme_dir\" && zip -v \"$output_relative_path\"" "${files[@]}"
elif (cd "$theme_dir" && zip -v "$output_relative_path" "${files[@]}"); then
  echo
  echo "${prefix}created: $output_file"
else
  exit_code=$?
  error "unable to create: $output_file" "$exit_code"
fi
